{ schema }:

let
  inherit (schema)
    freeformSubmodule
    optional
    optionalNonEmptyString
    optionalString
    optionalStringList
    optionalSubmodule
    required
    types
    ;
in
{
  name = optionalNonEmptyString "Human-readable browser name.";
  log_prefix = optionalNonEmptyString "Prefix used for log messages.";

  executable_name =
    required types.nonEmptyStr ''
      Name of the launcher generated by `browser apply`.
    ''
    // {
      example = "chromium";
    };

  alias_name = optionalNonEmptyString "Optional alias for the generated launcher.";
  flags_file = optionalString "Optional flags file read by the generated launcher.";
  flags = optionalStringList "Cross-platform Chromium command-line flags.";
  user_agent = optionalNonEmptyString ''
    Custom browser user agent passed with Chromium's `--user-agent` switch.
  '';

  linux = optionalSubmodule {
    app_dir = optionalString "Default Linux browser bundle directory.";
    desktop_id = optionalNonEmptyString ''
      Desktop identifier used for the Wayland application ID and X11 startup
      WM class.
    '';
    portal_app_id = optionalNonEmptyString ''
      Compiled-in D-Bus application ID Chromium registers with XDG Desktop
      Portal.
    '';
    wrapper_flags = optionalStringList "Additional flags always passed by the Linux launcher.";
    launcher_name = optionalNonEmptyString "Launcher name inside the browser bundle.";
    desktop_name = optionalNonEmptyString "Desktop-entry name inside the browser bundle.";
    desktop_exec = optionalNonEmptyString "Executable name replaced in desktop entries.";
    icon_name = optionalNonEmptyString "Installed desktop icon name.";
    icon_source = optionalNonEmptyString "Icon path relative to the browser bundle.";
  } "Linux-specific browser metadata.";

  macos = optionalSubmodule {
    app_dir = optionalString "Default macOS application bundle path.";
    launcher_path = optionalString "Launcher path relative to the application bundle.";
  } "macOS-specific browser metadata.";

  paths =
    required
      (types.attrsWith {
        elemType = freeformSubmodule {
          profile_dir = optionalString "Default Chromium profile directory.";
          external_extension_dirs = optionalStringList ''
            Directories receiving external-extension manifests.
          '';
        };
        placeholder = "installation-mode";
      })
      ''
        Per-installation-mode paths. `''${home}`, `''${config_home}`, and
        `''${data_home}` are expanded at runtime.
      ''
    // {
      default = { };
      example.linux = {
        profile_dir = "\${config_home}/chromium/Default";
        external_extension_dirs = [ "\${config_home}/chromium/External Extensions" ];
      };
    };

  preferences = optionalSubmodule (import ./preferences.nix { inherit schema; }) ''
    Declarative browser preference mutations.
  '';

  helium = optionalSubmodule (import ./helium.nix { inherit schema; }) ''
    Preferences implemented only by Helium.
  '';

  brave = optionalSubmodule (import ./brave.nix { inherit schema; }) ''
    Preferences implemented only by Brave.
  '';

  extension_id_aliases = optional (types.attrsOf schema.extensionId) ''
    Mapping from configured extension IDs to the IDs of installed variants.
  '';
}
