{
  lib,
  tomlFormat,
}:

let
  inherit (lib) mkOption types;

  freeformSubmodule =
    options:
    types.submodule {
      freeformType = tomlFormat.type;
      inherit options;
    };

  required = type: description: mkOption { inherit type description; };

  optional =
    type: description:
    required (types.nullOr type) description
    // {
      default = null;
    };

  optionalString = optional types.str;
  optionalNonEmptyString = optional types.nonEmptyStr;
  optionalStringList = optional (types.listOf types.str);
  optionalBool = optional types.bool;
  optionalInt = optional types.int;
  pathString = types.coercedTo types.path toString types.str;
  optionalUnsigned = optional types.ints.unsigned;
  optionalSubmodule = options: optional (freeformSubmodule options);

  extensionID = types.strMatching "[a-p]{32}";

  preferenceValue = freeformSubmodule {
    path = required types.nonEmptyStr "Dotted path of the value to update.";
    value = required types.toml "TOML value to write at `path`.";
  };

  accelerator = freeformSubmodule {
    path = required types.nonEmptyStr "Dotted path containing Chromium custom accelerators.";
    command_id = required types.nonEmptyStr "Chromium command identifier.";
    accelerator = required types.nonEmptyStr "Accelerator string to add.";
  };

  browserSettings = freeformSubmodule {
    name = optionalNonEmptyString "Human-readable browser name.";
    log_prefix = optionalNonEmptyString "Prefix used for log messages.";

    executable_name = mkOption {
      type = types.nonEmptyStr;
      example = "chromium";
      description = "Name of the launcher generated by `browser configure`.";
    };

    alias_name = optionalNonEmptyString "Optional alias for the generated launcher.";
    flags_file = optionalString "Optional flags file read by the generated launcher.";
    flags = optionalStringList "Cross-platform Chromium command-line flags.";
    user_agent = optionalNonEmptyString "Custom browser user agent passed with Chromium's `--user-agent` switch.";

    linux = optionalSubmodule {
      app_dir = optionalString "Default Linux browser bundle directory.";
      desktop_id = optionalNonEmptyString "Desktop identifier used for the Wayland application ID and X11 startup WM class.";
      portal_app_id = optionalNonEmptyString "Compiled-in D-Bus application ID Chromium registers with XDG Desktop Portal.";
      wrapper_flags = optionalStringList "Additional flags always passed by the Linux launcher.";
      launcher_name = optionalNonEmptyString "Launcher name inside the browser bundle.";
      desktop_name = optionalNonEmptyString "Desktop-entry name inside the browser bundle.";
      desktop_exec = optionalNonEmptyString "Executable name replaced in desktop entries.";
      icon_name = optionalNonEmptyString "Installed desktop icon name.";
      icon_source = optionalNonEmptyString "Icon path relative to the browser bundle.";
    } "Linux-specific browser metadata.";

    macos = optionalSubmodule {
      app_dir = optionalString "Default macOS application bundle path.";
      launcher_path = optionalString "Launcher path relative to the application bundle.";
    } "macOS-specific browser metadata.";

    paths = mkOption {
      type = types.attrsOf (freeformSubmodule {
        profile_dir = optionalString "Default Chromium profile directory.";
        external_extension_dirs = optionalStringList "Directories receiving external-extension manifests.";
      });
      default = { };
      example = {
        linux = {
          profile_dir = "\${config_home}/chromium/Default";
          external_extension_dirs = [ "\${config_home}/chromium/External Extensions" ];
        };
      };
      description = "Per-installation-mode paths. `\${home}`, `\${config_home}`, and `\${data_home}` are expanded at runtime.";
    };

    preferences = optionalSubmodule {
      values = optional (types.listOf preferenceValue) "Values written to Chromium Preferences.";
      local_state_values = optional (types.listOf preferenceValue) "Values written to Chromium Local State.";
      variation_values = optional (types.listOf preferenceValue) "Values written to Chromium Variations.";
      accelerators = optional (types.listOf accelerator) "Custom accelerator entries added to Preferences.";
      cookies = optionalSubmodule {
        default = optional (types.enum [
          "allow"
          "block"
          "session_only"
        ]) "Default cookie behavior.";
        third_party = optional (types.enum [
          "off"
          "block"
          "incognito_only"
        ]) "Chromium cookie-controls mode for third-party cookies.";
        allow = optionalStringList "Cookie patterns to allow; an empty list removes existing allow exceptions.";
        block = optionalStringList "Cookie patterns to block; an empty list removes existing block exceptions.";
        session_only = optionalStringList "Cookie patterns retained only for the current session.";
      } "Default, third-party, and per-site cookie policy.";
    } "Declarative browser preference mutations.";

    helium = optionalSubmodule {
      completed_onboarding = optionalBool "Whether Helium's onboarding has been completed.";
      crash_reporting = optional (types.enum [
        "disabled"
        "ask"
        "automatic"
      ]) "Helium crash-report upload mode.";

      services = optionalSubmodule {
        enabled = optionalBool "Allow Helium services globally.";
        user_consented = optionalBool "Record the user's consent to Helium services.";
        origin_override = optionalString "Custom HTTPS or localhost Helium services origin.";
        extension_proxy = optionalBool "Use Helium's privacy-preserving extension proxy.";
        bangs = optionalBool "Fetch and enable Helium's native search bangs.";
        spellcheck_files = optionalBool "Allow Helium to fetch spellcheck dictionaries.";
        browser_updates = optionalBool "Allow Helium browser or component update checks.";
        ublock_assets = optionalBool "Allow Helium to update its bundled uBlock assets.";
      } "Helium-only service controls.";

      toolbar = optionalSubmodule {
        show_back_button = optionalBool "Show Helium's back button.";
        show_reload_button = optionalBool "Show Helium's reload button.";
        show_avatar_button = optionalBool "Show Helium's avatar button.";
        show_extensions_button = optionalBool "Show Helium's extensions button.";
        show_menu_button = optionalBool "Show Helium's app-menu button.";
        show_media_button = optionalBool "Show Helium's media button.";
      } "Helium-only toolbar controls.";
    } "Preferences implemented only by Helium.";

    brave = optionalSubmodule {
      tabs = optionalSubmodule {
        hover_mode = optional (types.enum [
          "tooltip"
          "card"
          "card_with_preview"
        ]) "Brave tab-hover presentation.";
        vertical = optionalBool "Enable Brave vertical tabs.";
        collapsed = optionalBool "Collapse Brave vertical tabs.";
        expanded_state_per_window = optionalBool "Remember vertical-tab expansion per window.";
        show_window_title = optionalBool "Show the window title with vertical tabs.";
        hide_completely_when_collapsed = optionalBool "Fully hide collapsed vertical tabs.";
        floating = optionalBool "Use Brave's floating vertical tabs.";
        show_toggle_button = optionalBool "Show the vertical-tabs toggle.";
        expanded_width = optionalInt "Expanded vertical-tab width in pixels.";
        on_right = optionalBool "Place vertical tabs on the right.";
        show_scrollbar = optionalBool "Show the vertical-tab scrollbar.";
        tree = optionalBool "Enable Brave tree tabs.";
        shared_pinned = optionalBool "Share pinned tabs between windows.";
        always_hide_close_button = optionalBool "Always hide tab close buttons.";
        middle_click_close = optionalBool "Close a tab when it is middle-clicked.";
        min_width = optional (types.enum [
          "default"
          "minimum"
          "medium"
          "large"
          "full"
        ]) "Brave horizontal-tab minimum-width mode.";
        scrollable_horizontal = optionalBool "Use Brave's scrollable horizontal tab strip.";
        show_horizontal_scroll_buttons = optionalBool "Show horizontal tab-strip scroll buttons.";
        compact_horizontal = optionalBool "Use Brave's compact horizontal tab layout.";
      } "Brave-only tab controls.";

      sidebar = optionalSubmodule {
        show = optional (types.enum [
          "always"
          "mouseover"
          "never"
        ]) "When Brave's sidebar is shown.";
      } "Brave-only sidebar controls.";

      shields = optionalSubmodule {
        adblock_only_mode = optionalBool "Use Brave Shields in ad-block-only mode.";
        custom_filters = optionalString "Brave ad-block custom filter rules.";
        facebook_embeds = optionalBool "Allow Facebook embeds through Brave Shields.";
        twitter_embeds = optionalBool "Allow Twitter embeds through Brave Shields.";
        linkedin_embeds = optionalBool "Allow LinkedIn embeds through Brave Shields.";
      } "Brave Shields controls stored in Local State.";
    } "Preferences implemented only by Brave.";

    extension_id_aliases = optional (types.attrsOf extensionID) ''
      Mapping from configured extension IDs to the IDs of installed variants.
    '';
  };

  namedExtension = {
    id = mkOption {
      type = extensionID;
      example = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
      description = "Chromium extension identifier.";
    };

    name = optionalNonEmptyString "Human-readable extension name.";
  };

  chromeStoreExtension = freeformSubmodule namedExtension;

  updateURLExtension = freeformSubmodule (
    namedExtension
    // {
      update_url = required types.nonEmptyStr "Extension update manifest URL.";
    }
  );

  downloadedExtension = freeformSubmodule (
    namedExtension
    // {
      version = mkOption {
        type = types.strMatching "[0-9]+(\\.[0-9]+)*";
        example = "1.2.3";
        description = "Extension version.";
      };

      url = required types.nonEmptyStr "CRX download URL.";

      sha256 = mkOption {
        type = types.nonEmptyStr;
        example = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
        description = "CRX SHA-256 checksum in SRI, raw hex, or `sha256:<hex>` form.";
      };
    }
  );

  githubReleaseExtension = freeformSubmodule (
    namedExtension
    // {
      update_policy = optional (types.enum [
        "latest"
        "pinned"
      ]) "Use the latest GitHub release or a version/URL/SHA-256 pinned artifact.";

      version = optional (types.strMatching "[0-9]+(\\.[0-9]+)*") "Pinned extension version.";
      url = optionalNonEmptyString "Pinned ZIP download URL.";
      sha256 = optionalNonEmptyString "Pinned ZIP SHA-256 in SRI, raw hex, or `sha256:<hex>` form.";

      repository = optional (types.strMatching "[^/]+/[^/]+") ''
        GitHub repository used when `update_policy = "latest"`.
      '';

      asset_template = optionalNonEmptyString ''
        Latest-release asset name containing a `{tag}` placeholder.
      '';

      archive_root = optionalString "Path inside the release archive to install.";

      load_unpacked = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to load the installed extension as an unpacked extension.";
      };
    }
  );

  networkSettings = freeformSubmodule {
    chrome_version = optional (types.strMatching "[0-9]+(\\.[0-9]+)*") ''
      Chrome product version sent to the Chrome Web Store update service. If
      omitted, the latest Stable Chrome version is fetched at install time.
    '';
    user_agent = optionalNonEmptyString "User agent used for extension HTTP and GitHub requests.";
    headers = optional (types.attrsOf types.str) "Additional HTTP request headers.";
    timeout_seconds = optionalUnsigned "HTTP request timeout in seconds.";
    retry_max = optionalUnsigned "Maximum transient HTTP retries; zero disables retries.";
    retry_wait_min_milliseconds = optionalUnsigned "Minimum retry delay in milliseconds.";
    retry_wait_max_milliseconds = optionalUnsigned "Maximum retry delay in milliseconds.";
  };

  extensionSettings = freeformSubmodule {
    chrome_store_update_url = optionalString "Chrome Web Store update service URL.";
    network = optional networkSettings "HTTP identity, Chrome version, headers, timeouts, and retry policy.";
    chrome_store = optional (types.listOf chromeStoreExtension) "Extensions installed from the Chrome Web Store.";
    update_url = optional (types.listOf updateURLExtension) "Extensions installed through update manifests.";
    crx = optional (types.listOf downloadedExtension) "Checksum-pinned CRX extensions.";
    zip = optional (types.listOf githubReleaseExtension) "Latest or checksum-pinned unpacked ZIP extensions.";
  };

  extensionStorageSettings = freeformSubmodule {
    files = optional (types.listOf pathString) ''
      Ordered JSON extension-settings documents. Relative strings resolve from
      the generated TOML file; Nix paths are written as absolute store paths.
    '';
  };
in
freeformSubmodule {
  browser = required browserSettings "Browser identity, platform metadata, paths, and preference defaults.";
  extensions = optional extensionSettings "Optional extension installation catalog.";
  extension_settings = optional extensionStorageSettings ''
    JSON documents used to populate persistent chrome.storage.local and
    chrome.storage.sync data.
  '';
}
