name: Nix

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: nix-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          enable_kvm: true
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check the flake
        run: nix flake check --print-build-logs
